#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-velero
version: 1.7.1
description: Velero is an open source tool to safely backup and restore, perform disaster recovery, and migrate Kubernetes cluster resources and persistent volumes
keywords:
  - velero
home: https://github.com/Cray-HPE/cray-velero
dependencies:
  - name: velero
    version: 2.27.5
    repository: https://vmware-tanzu.github.io/helm-charts
maintainers:
  - name: bklei
  - name: cdelatte-hpe
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
- https://github.com/vmware-tanzu/velero
- https://github.com/vmware-tanzu/helm-charts
appVersion: 2.27.5
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-velero/issues/3
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-velero/pull/2
  artifacthub.io/images: |
    - name: docker-kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: velero
      image: artifactory.algol60.net/csm-docker/stable/docker.io/velero/velero:v1.7.1
    - name: velero-plugin-for-aws
      image: artifactory.algol60.net/csm-docker/stable/docker.io/velero/velero-plugin-for-aws:v1.3.1
    - name: velero-restic-restore-helper
      image: artifactory.algol60.net/csm-docker/stable/docker.io/velero/velero-restic-restore-helper:v1.7.1
  artifacthub.io/license: MIT
